### ISSUE TITLE
Issue nach update 

### ISSUE THREAD

**Issue by sfratz** [FreieRadios/joomla-template-bfr-2022#19]
0 There is no "table.columns" asset of a "script" type in the registry. 

Meldung nach Update Fehler
![grafik](https://user-images.githubusercontent.com/34003014/205465225-dc6a4fe1-79af-4c10-a373-3df3bd12eae5.png)

**Comment by lieblerm** [comment]
Bin dem Rat hier gefolgt und habe die Core-Dateien neu installiert: https://forum.joomla.de/thread/16560-joomla-4-es-ist-ein-fehler-aufgetreten-there-is-no-table-columns-asset-of-a-scri/

Im Backend via https://www.freie-radios.de/administrator/index.php?option=com_joomlaupdate
