### ISSUE TITLE
Karte ersetzen

### ISSUE THREAD

**Issue by sfratz** [FreieRadios/joomla-template-bfr-2022#4]
Karte soll mit umap umgesetzt werden. 
Beispiel https://umap.openstreetmap.fr/de/map/aff-radios_378246#8/48.652/9.176  

Daten sind in Joomla Destinations hinterlegt. Daraus müsste ein KML/geojson/... erzeugt werden, dass umap einlesen kann.
https://freie-radios.de/administrator/index.php?option=com_stations&view=destination

**Comment by lieblerm** [comment]
Geht das so? https://bfr.janguo.de/radios.html?format=json

**Comment by sfratz** [comment]
Irgendwie nicht auf Anhieb

http://umap.openstreetmap.fr/de/map/bundesverband-freier-radios_707878 

hab es so eingestellt, dass jeder bearbeiten kann, der den Link hat 

 

Sabine

**Comment by lieblerm** [comment]
Hmm.. Bearbeiten konnte ich leider nicht. 
Ich konnte aber diese Karte mit dem exportierten Json füllen: http://umap.openstreetmap.fr/de/map/test_707930.

Ich habe die aktuellen Daten vom Livesystem verwendet:  https://freie-radios.de/index.php?option=com_stations&view=category&id=63&format=json 
(63  => Freie Radios in Deutschland)

Problem: Ich konnte beim Import nicht die URL direkt eingeben, sondern musste das Json als Datei hochladen

Popup-Vorlage:

```{{{logo}}}
# {name}
{zipcode} {city}
{address}
[[{www}]]
{ukw}<br />
[[Livestream|{livestream}]]
````

**Comment by lieblerm** [comment]
Ich glaube jetzt geht es:  https://freie-radios.de/index.php?option=com_stations&view=category&id=63&format=json

Hinweis beachten "Mit Proxy": https://github.com/umap-project/umap/issues/720

**Comment by sfratz** [comment]
das sieht super aus - ich hab die von mir nochmal auf editieren geschaltet - beim ersten Mal nicht richtig funktioniert. http://u.osmfr.org/m/707878/ 
Für die endgültige Lösung kann man OSM User explizit als Bearbeiter hinzufügen. 
hatte das mit dem Proxy gestern schon mal probiert. Irgendwie nicht gegangen. 
Ich hab auch noch die Lizenz eingetragen. 
Auf jeden Fall super! Danke. 

Was sind Daten von "Livestream"? Gibt es da eine Doku, wo alle Livestreams gelistet sind? Wo wird das verwendet?

**Comment by lieblerm** [comment]
Da weiß ich nicht mehr die Geschichte dazu. Aber es gibt ja Radios ohne UKW-Frequenz, die nur im Internet senden. Dazu habe ich das Livestream-Feld gemacht. Da sind schon Daten erfasst, aber sicher nicht mehr aktuell. 

Vielleicht kann man jemanden gewinnen all diese Daten zu kontrollieren. Ein Logo-Feld habe ich auch hinzugefügt (bei Querfunk ist   eines eingetragen)

**Comment by lieblerm** [comment]
https://www.freie-radios.de/radios/karte.html

**Comment by sfratz** [comment]
> Da weiß ich nicht mehr die Geschichte dazu. Aber es gibt ja Radios ohne UKW-Frequenz, die nur im Internet senden. Dazu habe ich das Livestream-Feld gemacht. Da sind schon Daten erfasst, aber sicher nicht mehr aktuell.
> 
> Vielleicht kann man jemanden gewinnen all diese Daten zu kontrollieren. Ein Logo-Feld habe ich auch hinzugefügt (bei Querfunk ist eines eingetragen)

Die aktuellen Logos liegen alle in der Nextcloud vom BfR, die hab ich letztes Jahr eingesammelt. Mark will im Februar den Grafiker dran setzen für nen neuen Mitgliederflyer. Da könnte er vielleicht auch alle in das richtige Format bringen (ist nämlich wie Kraut und Rüben)

**Comment by sfratz** [comment]
Woltersdorf wurde nicht angezeigt - in den Geodaten war ein Komma zuviel und sie hatten keinen Livestream. Hab den von Pi eingetragen - jetzt sind sie auch drauf :)

**Comment by sfratz** [comment]
im Joomla Template für die Eingabe der Stationsdaten unter dem Feld für Frequenz würde ich den Text "ohne MHz" entfernen wollen:

Es hat sich gezeigt, dass das Feld oft für Zusatzinfos verwendet werden muss, weil z. B. Fensterzeiten mit ausgeben müssen (weil es sonst Ärger mit dem Frequenzpartner gibt) oder weil die Frequenzen in unterschiedlichen Orten liegen z. B. mit Mannheim und Heidelberg oder weil man auch auf DAB sendet - dann macht es keinen Sinn in einer Vorlage MHz generell hinten an zu setzen.

**Comment by lieblerm** [comment]
Dann müsste der Inhalt des Feldes für die meisten Radios in der Datenbank entsprechend geändert werden.

Hieße das Feld vielleicht besser auch "Empfang" mit mehrzeiliger Eingabemöglichkeit? 

Am 25. Januar 2022 23:06:51 MEZ schrieb sfratz ***@***.***>:
>im Joomla Template für die Eingabe der Stationsdaten unter dem Feld für Frequenz würde ich den Text "ohne MHz" entfernen wollen:
>
>
>
>Es hat sich gezeigt, dass das Feld oft für Zusatzinfos verwendet werden muss, weil z. B. Fensterzeiten mit ausgeben müssen (weil es sonst Ärger mit dem Frequenzpartner gibt) oder weil die Frequenzen in unterschiedlichen Orten liegen z. B. mit Mannheim und Heidelberg oder weil man auch auf DAB sendet - dann macht es keinen Sinn in einer Vorlage MHz generell hinten an zu setzen. >
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/FreieRadios/joomla-template-bfr-2022/issues/4#issuecomment-1021654003
>
>You are receiving this because you commented.
>
>
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by sfratz** [comment]
ja, würde sich anbieten - die Radios muss man eh alle anfassen wegen dem Logo - BW hab ich schon erledigt :)

**Comment by sfratz** [comment]
ich hab die umap Karte jetzt wieder nur für Bearbeiter bearbeiten zurück gesetzt - da müsste ich andere OSM Bearbeiter noch eintragen - Mark hat einen von Corax und ev. legen wir einen für den BfR an, dann können andere auch das Ausehen der Karte beeinflussen.

**Comment by lieblerm** [comment]
> ja, würde sich anbieten - die Radios muss man eh alle anfassen wegen dem Logo - BW hab ich schon erledigt :)

Ticket unter https://github.com/FreieRadios/joomla-stations-component/issues/7

**Comment by lieblerm** [comment]
> > ja, würde sich anbieten - die Radios muss man eh alle anfassen wegen dem Logo - BW hab ich schon erledigt :)
> 
> Ticket unter [FreieRadios/joomla-stations-component#7](https://github.com/FreieRadios/joomla-stations-component/issues/7)

Ist erledigt

**Comment by lieblerm** [comment]
Kann das geschlossen werden?

**Comment by sfratz** [comment]
ich bin mir Mark da noch dran, die Karte weg von meinem User auf einen
allgemeinen zu setzen

**Comment by sfratz** [comment]
das JSON File das aus der Station Erweiterung generiert wird beinhaltet auch den Umriss der Karte - kann man das trennen:

Wenn man die österreichischen oder schweizer Radios ausgeben will, dann kann man zwar durch Ändern des ID-String in der URL der JSon Datei zwar Geodaten der Sender in eine extra Ebene von umap reinladen, aber die Deutschlandkarte kommt dann immer mit. 

Wenn das viel Arbeit ist, dann lassen wir es so (im Moment benötigt man ja nur die deutschen Sender)... 
oder anders gefragt: Woher kommt der Umriss der Karte?

**Comment by sfratz** [comment]
@lieblerm - karte hab ich jetzt umgezogen auf einen bfr-Account - soll ich für die Frage mit dem Umriss (siehe vorheriger Kommentar) ein eigenes Ticket aufmachen oder willst das noch hier beantworten ?

**Comment by lieblerm** [comment]
Da es Codeänderungen nach sich zieht, mach ich ein neues Ticket.
