### ISSUE TITLE
Hilfe für Editoren

### ISSUE THREAD

**Issue by sfratz** [FreieRadios/joomla-template-bfr-2022#6]
Eine interne Hilfe wiki für die User wäre gut. z. B. ein Beitrag, den nur angemeldete User sehen und den man auf dem Dashboard anpinnt oder eine Kategorie, in der mehrere Beiträge erstellt werden, die nur angemeldete User sehen und die man dann als Modul auf das Dashboard pinnt oder ein extra Menü hat.

Konkret will ich dokumentieren, wie und wo man die Senderadressen für die Karte ändert.

**Comment by lieblerm** [comment]
Im backend unter Hilfe findest du jetzt das Modul "Hilfe für EditorInnen". Über das Kontext-Menü kannst du es bearbeiten und auch die Position auf das Start-Dasboard verlegen, in dem du unter Position "cpanel" wählst.

**Comment by sfratz** [comment]
ich hab die Zugriffsebene mal von "public" auf "registered" gestellt - soll ja nur für die Leute sein, die die Seite pflegen.
