### ISSUE TITLE
Disclaimer für Mailinglisten

### ISSUE THREAD

**Issue by sfratz** [FreieRadios/joomla-template-bfr-2022#7]
Liegt der Text für die Mailinglisten außerhalb von der Webseite? https://freie-radios.de/mailinglisten.html

Falls ja, bitte einen Disclaimer für die Bearbeitungszeit hinzufügen

_Wir bearbeiten die Freigabe so schnell wie es uns möglich ist. Bitte habt gegebenenfalls Verständnis für unsere ehrenamtlichen Strukturen._

Falls nein, bitte um Hilfe, wo das editiert werden kann :)

**Comment by lieblerm** [comment]
Für die Mailinglisten ist die Formularkomponente "Convert Forms" zuständig. Das entsprechende Formular bearbeitest du unter https://freie-radios.de/administrator/index.php?option=com_convertforms&view=form&layout=edit&id=1 

- Komponenten => Convert Forms => Formulare =>BFR-Mailinglisten 
- Hier in der Sidebar links das zweite Icon von oben anklicken (Landschaftssysmbol / Entwurf) und anschließend die Gruppe "Box" wählen. 
Deine Änderungen kannst du nun im Feld "Text Nachricht" vornehmen.

**Comment by sfratz** [comment]
ich hab keine Berechtigung für das Modul - ich glaub du müsstest mich mal zum Superuser machen ;-)

**Comment by lieblerm** [comment]
Du bist hiermit befördert. :-)
